/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CarbonAt: typeof import('~icons/carbon/at')['default']
    'Heroicons:moonSolid': typeof import('~icons/heroicons/moon-solid')['default']
    'Heroicons:sun': typeof import('~icons/heroicons/sun')['default']
    'Heroicons:sunFill': typeof import('~icons/heroicons/sun-fill')['default']
    'Heroicons:sunSolid': typeof import('~icons/heroicons/sun-solid')['default']
    'Heroicons:xMark': typeof import('~icons/heroicons/x-mark')['default']
    'Heroicons:XMark': typeof import('~icons/heroicons/x-mark')['default']
    'Heroicons:xmarkicon': typeof import('~icons/heroicons/xmarkicon')['default']
    'Heroicons:xMarkIcon': typeof import('~icons/heroicons/x-mark-icon')['default']
    IMdiAccount: typeof import('~icons/mdi/account')['default']
    'Mdi:account': typeof import('~icons/mdi/account')['default']
    'Mdi:at': typeof import('~icons/mdi/at')['default']
    'Mdi:bell': typeof import('~icons/mdi/bell')['default']
    'Mdi:chevronLeft': typeof import('~icons/mdi/chevron-left')['default']
    'Mdi:chevronRight': typeof import('~icons/mdi/chevron-right')['default']
    'Mdi:cog': typeof import('~icons/mdi/cog')['default']
    'Mdi:mapMarker': typeof import('~icons/mdi/map-marker')['default']
    'Mdi:phone': typeof import('~icons/mdi/phone')['default']
    'Mdi:plus': typeof import('~icons/mdi/plus')['default']
    MdiAt: typeof import('~icons/mdi/at')['default']
    MdiKey: typeof import('~icons/mdi/key')['default']
  }
}
